[package]
name = "mysql_async_orm"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql_async_orm_proc_macros = { path = "../mysql_async_orm_proc_macros" }
mysql_async = "0.29"
lazy_static = "1.4"